version: "3.3"
services:
  backend-quiz-db:
    container_name: backend-quiz-mysql-db
    image: mysql:5.7
    restart: always
    command: --sql_mode="NO_ENGINE_SUBSTITUTION"
    environment:
      MYSQL_DATABASE: "backend_quiz_db"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - vol-backend-quiz-db:/var/lib/mysql
volumes:
  vol-backend-quiz-db:
